apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    - host: "{{.Release.Name}}.{{ .Values.n8n.baseDomainName }}"
      http:
        paths:
          {{- if eq .Values.n8n.deploymentMode "scale" }}
          - path: /webhook/
            pathType: Prefix
            backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
          - path: /webhook-waiting/
            pathType: Prefix
            backend:
              service:
                name: n8n-webhook
                port:
                  number: 5678
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n-main
                port:
                  number: 5678
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
