apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  DB_POSTGRESDB_USER: {{ .Values.n8n.db.user | b64enc }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.n8n.db.password | b64enc }}
